

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email":"sammvuti@gmail.com",
    "password":"1234567668"
}

###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name":"samuel",
    "email":"sammvuti@gmail.com",
    "password":"1234567668",
    "course":"Informatica de Gestão",
    "year":2
}

###
GET http://localhost:8080/api/v1/material
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InNhbW12dXRpQGdtYWlsLmNvbSIsInJvbGUiOiIiLCJleHAiOjE3ODIyNTQ1MTQsImlhdCI6MTc4MjI0NzMxNH0.3Hqit8ymcnLHz1ZkHkljtOQR0QWO8jh7lhyF8L192Fk


###
POST http://localhost:8080/api/v1/material
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InNhbW12dXRpQGdtYWlsLmNvbSIsInJvbGUiOiIiLCJleHAiOjE3ODIyNTQ1MTQsImlhdCI6MTc4MjI0NzMxNH0.3Hqit8ymcnLHz1ZkHkljtOQR0QWO8jh7lhyF8L192Fk


{
    "title":"Prova de Rede de Computador",
    "description":"Prova da P2",
    "file_url":"google.com/21",
    "type_file":"Imagem"
}
