services:
  db:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: