# Generated by Django 6.1.1 on 2026-09-17 17:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alvo_tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('MENTOR', 'Mentor')], max_length=10)),
                ('alvo_id', models.PositiveIntegerField()),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('autor_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('autor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PALESTRA', 'Palestra'), ('WORKSHOP', 'Workshop'), ('ENCONTRO', 'Encontro')], max_length=20)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(max_length=150)),
                ('link_externo', models.URLField(blank=True, null=True)),
                ('organizador_nome', models.CharField(max_length=100)),
                ('organizador_email', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('curso', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('area', models.CharField(choices=[('PROGRAMACAO', 'Programação'), ('MATEMATICA', 'Matemática'), ('REDES', 'Redes'), ('SISTEMAS', 'Sistemas'), ('OUTRA', 'Outra')], max_length=20)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('dias_disponiveis', models.CharField(max_length=100)),
                ('horario_disponivel', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_publico', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('avaliacao_media', models.FloatField(default=0.0)),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=50)),
                ('extensao', models.CharField(max_length=20)),
                ('autor_nome', models.CharField(max_length=30)),
                ('autor_email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('avaliacao_media', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cadeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='core.cadeira')),
            ],
        ),
    ]
