# Generated by Django 6.1.1 on 2026-09-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='ficheiro',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
    ]
