# Generated by Django 6.1.1 on 2026-09-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_material_ficheiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
                ('contacto_publico', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('avaliacao_media', models.FloatField(default=0.0)),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
