# Generated by Django 6.1.1 on 2026-09-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mentoria_delete_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='link_externo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='organizador_email',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='organizador_nome',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
