# Generated by Django 6.1.1 on 2026-09-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_evento_hora_remove_evento_link_externo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='autor_email',
        ),
        migrations.RemoveField(
            model_name='material',
            name='autor_nome',
        ),
        migrations.RemoveField(
            model_name='material',
            name='extensao',
        ),
        migrations.RemoveField(
            model_name='material',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='material',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
