# Generated by Django 6.1.1 on 2026-09-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_material_autor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='motivo_rejeicao',
        ),
        migrations.RemoveField(
            model_name='material',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='mentoria',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='mentoria',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='mentoria',
            name='motivo_rejeicao',
        ),
    ]
