# Generated by Django 6.1.1 on 2026-09-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='ficheiro',
            field=models.FileField(blank=True, null=True, upload_to='conteudos/'),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='conteudo',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='titulo',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('identificador_visitante', models.CharField(max_length=64)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='conteudo.conteudo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conteudo', 'identificador_visitante'), name='uma_avaliacao_por_visitante')],
            },
        ),
    ]
