# Generated by Django 6.1.1 on 2026-09-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_conteudo_ficheiro_alter_conteudo_conteudo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidaturaMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('area', models.CharField(max_length=120)),
                ('apresentacao', models.TextField(max_length=1200)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sugestao', 'Sugestão'), ('critica', 'Crítica'), ('elogio', 'Elogio')], default='sugestao', max_length=20)),
                ('mensagem', models.TextField(max_length=1000)),
                ('contacto', models.EmailField(blank=True, max_length=254)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
