# Generated by Django 6.1.1 on 2026-09-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_candidaturamentor_sugestao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
