CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL, 
    course VARCHAR(50) NOT NULL,
    year INTEGER NOT NULL,
    role  VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS materias(
	id SERIAL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	description TEXT,
	file_url TEXT NOT NULL,
	document_type VARCHAR(20) NOT NULL,
	point INTEGER DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
