basePath: /api/v1
definitions:
  domain.UserLogin:
    properties:
      email:
        type: string
      password:
        minLength: 5
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: Servidor de testes de rotas e estresse.
  title: API de Autenticação
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Autentica o usuário com e-mail e senha e devolve um token JWT
      parameters:
      - description: Credenciais de Acesso
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: 'token: jwt_token'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 'erro: dados inválidos'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Realiza o login do usuário
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Cadastra o usuário
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Realiza o cadastro do usuário
      tags:
      - Auth
swagger: "2.0"
