# Generated by Django 6.1.1 on 2026-10-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('ano', models.PositiveSmallIntegerField(choices=[(1, '1º Ano'), (2, '2º Ano'), (3, '3º Ano'), (4, '4º Ano'), (5, '5º Ano')])),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')])),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='APROVADO', max_length=10)),
                ('ficheiro', models.FileField(upload_to='materias/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
